name: Build

on: [push, pull_request]

permissions:
  # Required for Electron Builder to create and update releases on Github
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os}}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build
        shell: bash
        run: |
          if [ "${{ github.head_ref || github.ref_name }}" = "main" ]; then
            npm run build -- --x64 --arm64
          else
            npm run build -- --x64 --arm64 --publish=never
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
